### ISSUE TITLE
Review validation for empty tags

### ISSUE THREAD

**Issue by lukefretwell** [civichackingagency/dotgov-metadata#23]
Noticed the keywords for nasa.gov are empty but we show that they have, so should figure out how to address that:

`<meta name="keywords" content=""/>`

https://dotgov-metadata.civichackingagency.org/profile.html?domain=nasa.gov

**Comment by lukefretwell** [comment]
Note cia.gov `og:url` is empty but we're validating as active:

`<meta data-react-helmet="true" property="og:url" content=""/>`

https://dotgov-metadata.civichackingagency.org/profile.html?domain=cia.gov

**Comment by lukefretwell** [comment]
Same with cia.gov `og:image`:

`<meta data-react-helmet="true" property="og:image" content=""/>`

**Comment by Narlotl** [comment]
https://github.com/civichackingagency/dotgov-metadata/commit/4a16afbc106de5867c6a8b409a828c36887fe5b3
